# Generated by Django 3.0.6 on 2020-05-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20200511_0257'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heroinfo',
            table='heroinfo',
        ),
    ]
